# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

theme: metro
# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'KolaKuli'
tagline:          'Always'
description:      'Jekyll Metro'
url:              'http://192.168.1.11:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'KolaKuli'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com'
flickr:
github:         'https://github.com'
gplus:          'https://plus.google.com'
instagram:
pinterest:
linkedin:       'https://linkedin.com'
rss:
stackoverflow:  'http://stackoverflow.com'
twitter:        'https://twitter.com'

# Google Analytics
gahandler: 'UA'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'kolakuli'

# txtpen
txtpenhandler: 'kolakuli'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
